name: Update README

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test issue-list-action

    steps:
      - uses: actions/checkout@v3
      - uses: Bpazy/issue-list-action@master
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
