name: Update README

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test issue-list-action

    steps:
      - uses: actions/checkout@v3
      - uses: Bpazy/issue-list-action@dev
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
