name: Update README

on:
  workflow_dispatch:
  schedule:
   - cron: '0 */1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test issue-list-action

    steps:
      - uses: actions/checkout@v3
      - uses: Bpazy/issue-list-action@dev
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
